services:
  users:
    build:
      context: .
      target: dev
    container_name: users-service
    ports:
      - "${PORT}:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - SERVICE_TOKEN=${SERVICE_TOKEN}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - AUTH_ALGORITHM=HS256
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    networks:
      - melodia-net

networks:
  melodia-net:
    external: true
