services:
  users-test-db:
    image: postgres:16.3-bookworm
    container_name: users-test-db
    environment:
      POSTGRES_DB: melodia_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - test-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d melodia_test -h users-test-db || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  users-integral-tests:
    build:
      context: .
      target: test
    container_name: users-integral-tests
    env_file: .env.test
    environment:
      COVERAGE_DIR: /app/coverage_reports
    networks:
      - test-net
    depends_on:
      users-test-db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./coverage_reports:/app/coverage_reports
    command: >
      bash -c '
      pip install pytest-cov &&
      mkdir -p /app/coverage_reports &&
      PYTHONPATH=/app python -m pytest tests/integral \
        -c pytest_integral.ini \
        --maxfail=1 \
        --disable-warnings \
        --cov=app \
        --cov-report=xml:/app/coverage_reports/coverage.xml \
        --cov-report=html:/app/coverage_reports/html \
        --cov-report=term
      '

  users-tests:
    build:
      context: .
      target: test
    container_name: users-tests
    env_file: .env.test
    networks:
      - test-net
    depends_on:
      - users-test-db

networks:
  test-net:
    external: false
