services:
  users:
    build:
      context: .
      target: dev
    container_name: users-service
    env_file: .env
    ports:
      - "${PORT:-8002}:8002"
    networks:
      - melodia-net

networks:
  melodia-net:
    external: true
